apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: beny18241/complex-client
      ports:
        - containerPort:  3000
